[package]
name = "photogrid"
version = "0.1.0"
edition = "2021"

[dependencies]
grid = { path = "../grid" }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.127"
url = { version = "2.5.2", features = ["serde"] }


[dev-dependencies]
cool_asserts = "2.0.3"
